name: Deploy to an EC2
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create PEM file from secret
              run: echo "${{ secrets.EC2_PEM_KEY }}" | base64 -d > /tmp/ec2-key.pem

            - name: Set file permissions
              run: chmod 400 /tmp/ec2-key.pem

            - name: Deploy to EC2
              env:
                  HOST: ${{ secrets.EC2_HOST }}
                  USER: ec2-user
              run: |
                  scp -i /tmp/ec2-key.pem -o StrictHostKeyChecking=no -r ./* $USER@$HOST:/home/ec2-user/your-app
                  ssh -i /tmp/ec2-key.pem -o StrictHostKeyChecking=no $USER@$HOST '
                    cd /home/ec2-user/your-app
                    git pull origin main
                    npm install
                    pm2 restart all
                  '
